const state={lang:localStorage.getItem("coptic-lang")||"de",route:location.hash.replace("#","")||"home"};
const D={
de:{
welcome:"Herzlich willkommen",sub:"Schön, dass Sie da sind!",next:"Nächste Liturgie",sun:"Sonntag • 10:00",church:"Kirche",spiritual:"Spiritualität",media:"Medien",community:"Community",sunday:"Sonntagsschule",discover:"Entdecken",
notice:"Aktuelle Hinweise",noticeText:"Platzhalter für wichtige Nachrichten der Kirche.",churchSub:"Unsere Kirche, ihre Geschichte und unser Patron",spiritualSub:"Dein täglicher geistlicher Weg",mediaSub:"Videos, Bilder, Predigten und Lerninhalte",communitySub:"Verbinden, helfen und ankommen",
classTitle:"Sonntagsschule",classSub:"Separate App",open:"Sonntagsschule App öffnen",profile:"Profil & Einstellungen",back:"Home",
classes:[["Malayka / Angels","Gruppe 1","6–8 Jahre","assets/malayka.jpeg"],["Ava Kerelos","Gruppe 2","9–14 Jahre","assets/ava-kerelos.jpeg"],["Abouna Faltaous","Gruppe 3","15–20 Jahre","assets/abouna-faltaous.jpeg"]],
churchCards:[["▦","Gottesdienste","Liturgien & Termine","liturgies"],["▣","Veranstaltungen","Gemeinschaft & Termine","events"],["ⓘ","Über unsere Kirche","Kopten, Geschichte & Glaube","about"],["✣","Heiliger Markus","Gründer der koptischen Kirche","markus"],["♜","Unser Kirchenpatron","St. Petrus von Alexandria","petrus"],["♟","Papst Tawadros II","Das heutige Kirchenoberhaupt","tawadros"],["♟","Unsere Priester","Geistliche Begleitung","priests"],["⌖","Kontakt & Anfahrt","Adresse & Ansprechpartner","contact"]],
spiritualCards:[["▤","Bibel","Lesen & entdecken","bible"],["✓","Ein-Jahres-Leseplan","Dein täglicher Bibelweg","reading-plan"],["♢","Agpeya","Deutsch & Arabisch","agpeya"],["✚","Koptischer Kalender","Synaxar & Heilige","calendar"],["♡","Meine Favoriten","Gespeicherte Inhalte","favorites"]],
mediaCards:[["▶","Videos","Predigten, Lehre & Meditation","videos"],["◉","Bilder","Gemeindeleben & Veranstaltungen","images"],["♫","Predigten","Audio & geistliche Impulse","sermons"],["📚","Lerninhalte","Unterricht & Glaubenswissen","learning"],["✣","Empfohlen","Ausgewählte geistliche Inhalte","featured"]],
communityCards:[["⌂","Wohnen","Hilfe & Angebote"],["▣","Jobs","Hilfe & Angebote"],["🎓","Bildung","Hilfe & Angebote"],["♧","Allgemeine Hilfe","Gemeinschaft"],["♥","Neu in Hamburg?","Ankommen & verbinden"],["☼","Veranstaltungen","Menschen treffen"]],
profileSub:"Sprache, Benachrichtigungen & Konto",
aboutTitle:"Die koptisch-orthodoxe Kirche",aboutText:"Die Kopten sind Ägypter; im koptischen Christentum leben Elemente der ägyptischen Geschichte und Kultur fort. Die koptische Kirche blickt auf eine lange Geschichte und ehrwürdige Traditionen zurück.",markusText:"Die Gemeinde verehrt den Evangelisten und Apostel Markus als Gründer der koptischen Kirche. Die Website beschreibt ihre Gründung in Ägypten im 1. Jahrhundert und Markus als ersten Patriarchen; er starb als Märtyrer.",tawadrosText:"Papst Tawadros II ist das heutige Oberhaupt der koptisch-orthodoxen Kirche. In der App soll dieser Bereich später mit einem aktuellen, kirchlich freigegebenen Profil ergänzt werden.",
petrusTitle:"Der Heilige Petrus",petrusSub:"St. Petrus I. von Alexandria",petrusText:"St. Petrus I. von Alexandria wird als heiliger Märtyrer und Priesteroberhaupt beschrieben. Sein koptischer Gedenktag ist der 25. November; die Weihe seiner Kirche bei Alexandria wird am 26. Januar begangen. Er wird auch in der Basilius-Anaphora bedacht. Sein Name bedeutet „der Fels“ und stammt aus dem Griechischen bzw. Lateinischen.",petrusExtra:"St. Petrus wurde in Alexandria in Ägypten geboren und starb im November 311 in Baukalis, heute ein Teil Alexandrias. Nach den Bischofslisten war er der 17. Patriarch von Alexandria und wurde um 300 Nachfolger des Patriarchen Theonas. Während der Verfolgungen unter Kaiser Diokletian floh er um 306. Gegenüber Christen, die unter der Bedrängnis vom Glauben abgefallen waren, war er milde. Daraus entstand eine Spaltung der alexandrinischen Kirche und ein Gegenpatriarchat unter Melitius von Lykopolis; dieser wurde 306/307 durch eine Synode in Alexandria abgesetzt. Nach dem Toleranzedikt des Kaisers Galerius von 311, das die Christenverfolgung beendete und das Christentum als erlaubte Religion anerkannte, kehrte Petrus in sein Amt zurück. Kurz danach wurde er unter Galerius’ Nachfolger Maximinus Daia in Baukalis getötet – an derselben Stelle, an der auch Markus getötet worden sein soll. Die Website nennt Schriften von Petrus „Über die Gottheit Christi“, „Über das Passah-/Osterfest“, „Über die Seele“ und „Über die Auferstehung“; sie sind nur fragmentarisch in Zitaten erhalten. Petrus gilt außerdem als erster Bischof, der Maria den Beinamen „Eparthenos – fortwährende Jungfrau“ gab. Zusammen mit ihm werden Hesychius sowie die in Ägypten wirkenden Bischöfe Pachomius und Theodor und viele weitere Märtyrer aus den Jahren 305 bis 311 verehrt. Die später verfassten Märtyrerakten über die Verhandlungen gegen Petrus werden auf der Website als legendär eingeordnet. In der koptischen Kirche gilt Petrus als letztes Opfer der Verfolgungen und wird deshalb „Siegel der Märtyrer“ genannt.",
contactText:"Kontakt, Pfarrer und Sitz der koptisch-orthodoxen Kirchen in Norddeutschland.",contactPriest:"Vater Athanasius Basta Badres",contactPhone:"+49 1525 9544511",contactMonastery:"Koptisch-Orthodoxes Kloster der Jungfrau Maria und des heiligen Mauritius",contactAddress:"Propsteistrasse 1a • 37671 Höxter",contactBishop:"Seine Exzellenz Abba Damian • Bischof von Norddeutschland",contactBishopPhone:"+49 172 5643647",
mediaNote:"Die bestehende Website führt aktuell einen Medienbereich mit älteren Beispielereignissen. V1.2 macht daraus bewusst eine zukunftsfähige Medienbibliothek; echte Inhalte werden später über CMS/Redaktion gepflegt."
},
ar:{
welcome:"أهلاً وسهلاً بك",sub:"سعداء بوجودك معنا!",next:"القداس القادم",sun:"الأحد • 10:00",church:"الكنيسة",spiritual:"الحياة الروحية",media:"الإعلام",community:"المجتمع",sunday:"مدرسة الأحد",discover:"اكتشف",
notice:"أهم الإعلانات",noticeText:"مكان مخصص لأهم أخبار وإعلانات الكنيسة.",churchSub:"كنيستنا وتاريخها وشفيع الكنيسة",spiritualSub:"رحلتك الروحية اليومية",mediaSub:"فيديوهات وصور وعظات ومحتوى تعليمي",communitySub:"نتواصل ونساعد بعضنا البعض",
classTitle:"مدرسة الأحد",classSub:"تطبيق مستقل",open:"فتح تطبيق مدرسة الأحد",profile:"الحساب والإعدادات",back:"الرئيسية",
classes:[["ملايكة / Angels","المجموعة ١","٦–٨ سنوات","assets/malayka.jpeg"],["أفا كيرلس","المجموعة ٢","٩–١٤ سنة","assets/ava-kerelos.jpeg"],["أبونا فلتاؤس","المجموعة ٣","١٥–٢٠ سنة","assets/abouna-faltaous.jpeg"]],
churchCards:[["▦","القداسات","المواعيد والصلوات","liturgies"],["▣","الفعاليات","الأنشطة والمناسبات","events"],["ⓘ","عن الكنيسة","الأقباط والتاريخ والإيمان","about"],["✣","القديس مرقس","مؤسس الكنيسة القبطية","markus"],["♜","شفيع كنيستنا","القديس بطرس السكندري","petrus"],["♟","البابا تواضروس الثاني","الرئيس الحالي للكنيسة","tawadros"],["♟","الآباء الكهنة","الإرشاد الروحي","priests"],["⌖","التواصل والوصول","العنوان وبيانات التواصل","contact"]],
spiritualCards:[["▤","الكتاب المقدس","قراءة واكتشاف","bible"],["✓","خطة قراءة سنة","رحلتك اليومية مع الكتاب","reading-plan"],["♢","الأجبية","بالعربية والألمانية","agpeya"],["✚","التقويم القبطي","السنكسار والقديسون","calendar"],["♡","المفضلة","المحتوى المحفوظ","favorites"]],
mediaCards:[["▶","الفيديوهات","وعظ وتعليم وتأمل","videos"],["◉","الصور","حياة الكنيسة والفعاليات","images"],["♫","العظات","صوتيات وتأملات روحية","sermons"],["📚","محتوى تعليمي","التعليم ومعرفة الإيمان","learning"],["✣","محتوى مقترح","اختيارات روحية","featured"]],
communityCards:[["⌂","السكن","مساعدة وعروض"],["▣","الوظائف","مساعدة وفرص"],["🎓","التعليم","مساعدة وفرص"],["♧","مساعدة عامة","معاً نخدم بعضنا"],["♥","جديد في هامبورج؟","تعرف على المجتمع"],["☼","الفعاليات","نتعرف على بعضنا"]],
profileSub:"اللغة والإشعارات والحساب",
aboutTitle:"الكنيسة القبطية الأرثوذكسية",aboutText:"الأقباط هم المصريون، وتستمر في المسيحية القبطية بعض عناصر التاريخ والثقافة المصرية. للكنيسة القبطية تاريخ طويل وتقاليد عريقة.",markusText:"تكرّم الكنيسة القبطية الإنجيلي والرسول مرقس كمؤسس للكنيسة القبطية. ويصف موقع الكنيسة تأسيسها في مصر في القرن الأول ومرقس كأول بطريرك، وقد استشهد عام 68م.",tawadrosText:"البابا تواضروس الثاني هو الرئيس الحالي للكنيسة القبطية الأرثوذكسية. سيُضاف لاحقاً إلى هذا القسم ملف تعريفي حديث بعد اعتماده كنسياً.",
petrusTitle:"القديس بطرس",petrusSub:"القديس بطرس الأول بابا الإسكندرية",petrusText:"يصف موقع الكنيسة القديس بطرس الأول بابا الإسكندرية بأنه شهيد ورئيس كهنة. عيده القبطي في 25 نوفمبر، وتُذكر ذكرى تدشين كنيسته قرب الإسكندرية في 26 يناير، كما يُذكر اسمه في أنفورا القديس باسيليوس. ويعني اسمه «الصخرة» وهو اسم ذو أصل يوناني/لاتيني.",petrusExtra:"وُلد القديس بطرس في الإسكندرية بمصر، واستشهد في نوفمبر سنة 311 في بوكاليس، وهي منطقة في الإسكندرية اليوم. وبحسب قوائم البطاركة كان البطريرك السابع عشر للإسكندرية، وخلف البابا ثاؤنا حوالي سنة 300. أثناء الاضطهادات في عهد الإمبراطور دقلديانوس هرب حوالي سنة 306. وكان رحيماً مع الذين سقطوا عن الإيمان تحت شدة الاضطهاد، مما أدى إلى انقسام في كنيسة الإسكندرية وظهور بطريرك منافس هو مليتيوس أسقف ليكوبوليس، وقد عزلته مجمع الإسكندرية سنة 306/307. وبعد مرسوم التسامح الذي أصدره الإمبراطور جاليريوس سنة 311، والذي أنهى اضطهاد المسيحيين وجعل المسيحية ديانة مسموحاً بها، عاد بطرس إلى كرسيه. وبعد ذلك بقليل استشهد في عهد مكسيمينوس دايا، خليفة جاليريوس، في بوكاليس، في الموضع نفسه الذي يُذكر أن القديس مرقس استشهد فيه. وينسب إليه الموقع كتابات «عن لاهوت المسيح»، و«عن الفصح/عيد القيامة»، و«عن النفس»، و«عن القيامة»، ولم يبق منها إلا أجزاء في اقتباسات. ويُذكر أيضاً أن القديس بطرس كان أول أسقف أطلق على القديسة مريم لقب «إيبارثينوس – الدائمة البتولية». ويُكرّم معه الأسقف هيسيخيوس والأساقفة باخوميوس وثيؤدور الذين خدموا في مصر، إلى جانب كثيرين من الشهداء الذين استشهدوا بين عامي 305 و311. أما محاضر محاكمته التي كُتبت في زمن متأخر جداً، فيصفها الموقع بأنها تحمل عناصر أسطورية. وتعتبره الكنيسة القبطية آخر ضحايا الاضطهادات، ولذلك يُلقب بـ«خاتم الشهداء».",
contactText:"بيانات التواصل والكاهن ومقر الكنيسة القبطية الأرثوذكسية في شمال ألمانيا.",contactPriest:"الأب أثناسيوس باستا بدر",contactPhone:"+49 1525 9544511",contactMonastery:"دير السيدة العذراء مريم والقديس موريس",contactAddress:"Propsteistrasse 1a • 37671 Höxter",contactBishop:"نيافة الأنبا دميان • أسقف شمال ألمانيا",contactBishopPhone:"+49 172 5643647",
mediaNote:"يعرض موقع الكنيسة حالياً قسمًا للإعلام يحتوي على أمثلة لفعاليات قديمة. لذلك يحوّل V1.2 هذا القسم إلى مكتبة إعلامية قابلة للتطوير، على أن تُدار المواد الحقيقية لاحقاً عبر نظام محتوى."
}};
function t(k){return D[state.lang][k]??k}
function setLang(x){state.lang=x;localStorage.setItem("coptic-lang",x);render()}
function go(x){state.route=x;location.hash=x;render();window.scrollTo({top:0,behavior:"smooth"})}
function quick(icon,title,route,cls,sub){return `<button class="quick ${cls}" onclick="go('${route}')"><div class="quick-icon">${icon}</div><strong>${title}</strong><span>${sub||""}</span><i>›</i></button>`}
function featureCards(items){return `<div class="card-grid">${items.map(x=>`<button class="feature-card" onclick="go('${x[3]}')"><div class="ficon">${x[0]}</div><strong>${x[1]}</strong><span>${x[2]}</span></button>`).join("")}</div>`}
function pageHero(title,sub){return `<section class="page-hero"><button class="back" onclick="go('home')">‹ ${t("back")}</button><h1>${title}</h1><p>${sub}</p></section>`}
function home(){const c=t("classes");return `<div class="home-hero"><div class="hero-overlay"><div class="hero-copy"><div class="eyebrow">St. Petrus • Hamburg</div><h1>${t("welcome")}</h1><p>${t("sub")}</p><div class="hero-row"><span class="pill">✣ &nbsp; Koptisch-Orthodox</span><div class="lang-toggle"><button class="${state.lang==="de"?"active":""}" onclick="setLang('de')">DE</button><button class="${state.lang==="ar"?"active":""}" onclick="setLang('ar')">عربي</button></div></div></div></div></div><div class="home-body"><div class="liturgy-wrap"><div class="section-head compact"><h2>${t("next")}</h2><span>${t("sun")}</span></div><button class="liturgy"><div class="liturgy-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="5" width="16" height="15" rx="2"></rect><path d="M8 3v4M16 3v4M4 9h16M8 13h2M14 13h2M8 17h2"></path></svg></div><div class="liturgy-copy"><div class="label">${t("next")}</div><strong>${t("sun")}</strong><span>St. Petrus • Hamburg</span></div><div class="chev">›</div></button></div><div class="section-head discover-head"><h2>${t("discover")}</h2><button class="see-all" onclick="go('church')">${state.lang==="ar"?"عرض الكل":"Alle anzeigen"} ›</button></div><div class="quick-grid">${quick("⛪",t("church"),"church","q-blue","Unsere Gemeinde")}${quick("📖",t("spiritual"),"spiritual","q-blue","Bibel, Agpeya & Kalender")}${quick("▶",t("media"),"media","q-gold","Videos, Bilder & Predigten")}${quick("👥",t("community"),"community","q-green","Wohnen, Jobs & Hilfe")}</div><div class="ss-banner-home"><div class="ss-copy-home"><div class="eyebrow">${state.lang==="ar"?"مدرسة الأحد": "SONNTAGSSCHULE"}</div><h2>${state.lang==="ar"?"أطفالنا مستقبلنا":"Unsere Kinder<br>Unsere Zukunft"}</h2><p>${state.lang==="ar"?"إيمان • معرفة • مجتمع":"Glaube • Wissen • Gemeinschaft"}</p><button onclick="go('sunday')">${t("open")} <span>›</span></button></div><div class="ss-people">${c.map((x,i)=>`<button class="ss-person" onclick="go('class${i}')"><img src="${x[3]}" alt="${x[0]}"><strong>${x[0]}</strong><span>${x[1]}</span><em>${x[2]}</em></button>`).join("")}</div></div><div class="notice home-notice"><div class="notice-icon">📢</div><p><b>${t("notice")}</b><br>${t("noticeText")}</p><span class="notice-chevron">›</span></div><div class="home-today"><div class="home-today-head"><h3>${state.lang==="ar"?"اليوم في الكنيسة":"Heute in der Gemeinde"}</h3><span>${state.lang==="ar"?"هذا الأسبوع":"Diese Woche"}</span></div><div class="home-today-grid"><div class="today-item"><div class="today-icon">✚</div><b>${state.lang==="ar"?"الحياة الروحية":"Spiritueller Impuls"}</b><span>${state.lang==="ar"?"محتوى يومي للصلاة والتأمل":"Täglicher Inhalt für Gebet & Meditation"}</span></div><div class="today-item"><div class="today-icon">▣</div><b>${state.lang==="ar"?"المواعيد القادمة":"Nächster Termin"}</b><span>${state.lang==="ar"?"القداس والأحداث القادمة":"Liturgie & kommende Veranstaltungen"}</span></div></div></div></div>`}
function contentPage(title,sub,icon,body,extra=""){return `${pageHero(title,sub)}<div class="content-card"><div class="content-icon">${icon}</div>${body}${extra}</div>`}
function infoBody(title,text){return `<h2>${title}</h2><p>${text}</p>`}
function page(route){
if(route==="church")return `${pageHero(t("church"),t("churchSub"))}${featureCards(t("churchCards"))}`;
if(route==="spiritual")return `${pageHero(t("spiritual"),t("spiritualSub"))}${featureCards(t("spiritualCards"))}`;
if(route==="media")return `${pageHero(t("media"),t("mediaSub"))}${featureCards(t("mediaCards"))}<div class="media-note">💡 ${t("mediaNote")}</div>`;
if(route==="community")return `<section class="community-hero"><div class="eyebrow">St. Petrus • Hamburg</div><h1>${t("community")}</h1><p>${t("communitySub")}</p></section><div class="community-grid">${t("communityCards").map(x=>`<button class="community-item" onclick="placeholder('${x[1]}')"><div class="ci">${x[0]}</div><strong>${x[1]}</strong><span>${x[2]}</span></button>`).join("")}</div>`;
if(route==="profile")return `${pageHero(t("profile"),t("profileSub"))}<div class="profile-card" style="margin-top:13px"><div class="avatar">✣</div><div><h3>St. Petrus Hamburg</h3><p>${state.lang==="ar"?"إعدادات التطبيق واللغة":"App-Einstellungen und Sprache"}</p></div></div><div class="section-head"><h2>${state.lang==="ar"?"اللغة":"Sprache"}</h2></div><div class="lang-toggle lang-panel"><button class="${state.lang==="de"?"active":""}" onclick="setLang('de')">Deutsch</button><button class="${state.lang==="ar"?"active":""}" onclick="setLang('ar')">العربية</button></div>`;
if(route==="notifications")return contentPage(state.lang==="ar"?"الإشعارات":"Benachrichtigungen",state.lang==="ar"?"أخبار وتنبيهات الكنيسة":"Neuigkeiten und wichtige Hinweise der Kirche","🔔",`<h2>${state.lang==="ar"?"لا توجد إشعارات جديدة":"Keine neuen Benachrichtigungen"}</h2><p>${state.lang==="ar"?"هنا ستظهر لاحقاً إعلانات الكنيسة ومواعيد مهمة وتنبيهات مخصصة للمستخدم.":"Hier erscheinen später Kirchenankündigungen, wichtige Termine und personalisierte Hinweise."}</p>`);
if(route==="about")return contentPage(t("aboutTitle"),t("church"),"ⓘ",infoBody(t("aboutTitle"),t("aboutText")),`<div class="timeline"><div><b>1. Jahrhundert</b><span>Die Website verortet die Gründung der koptischen Kirche in Ägypten im 1. Jahrhundert.</span></div><div><b>Heiliger Markus</b><span>${t("markusText")}</span></div><div><b>Heute</b><span>${t("tawadrosText")}</span></div></div>`);
if(route==="markus")return contentPage(t("markusText").split(".")[0],t("church"),"✣",`<h2>${state.lang==="ar"?"مرقس الرسول":"Markus der Evangelist und Apostel"}</h2><p>${t("markusText")}</p>`);
if(route==="tawadros")return contentPage(state.lang==="ar"?"البابا تواضروس الثاني":"Papst Tawadros II",t("church"),"♟",`<h2>${state.lang==="ar"?"الرئيس الحالي للكنيسة":"Heutiges Kirchenoberhaupt"}</h2><p>${t("tawadrosText")}</p>`);
if(route==="petrus")return contentPage(t("petrusTitle"),t("petrusSub"),"♜",`<h2>${t("petrusSub")}</h2><div class="fact-row"><span>25.11.</span><b>${state.lang==="ar"?"العيد القبطي للقديس":"Koptischer Gedenktag"}</b></div><div class="fact-row"><span>26.01.</span><b>${state.lang==="ar"?"ذكرى تدشين كنيسته قرب الإسكندرية":"Weihe seiner Kirche bei Alexandria"}</b></div><div class="fact-row"><span>${state.lang==="ar"?"الاسم":"Name"}</span><b>${state.lang==="ar"?"الصخرة – يوناني/لاتيني":"„der Fels“ – griechisch/lateinisch"}</b></div><div class="fact-row"><span>${state.lang==="ar"?"المكان":"Ort"}</span><b>${state.lang==="ar"?"الإسكندرية / بوكاليس":"Alexandria / Baukalis"}</b></div><p>${t("petrusText")}</p><p>${t("petrusExtra")}</p><div class="source-note">${state.lang==="ar"?"المصدر: صفحة القديس بطرس على موقع الكنيسة. بعض التفاصيل التاريخية تُعرض كما يوردها المصدر، مع الإشارة إلى أن محاضر الشهادة المتأخرة تحمل عناصر أسطورية.":"Quelle: Petrus-Seite der Kirchenwebsite. Historische Angaben werden entsprechend der Quelle dargestellt; die Website weist selbst darauf hin, dass die späteren Märtyrerakten legendäre Elemente enthalten."}</div>`);
if(route==="contact")return contentPage(state.lang==="ar"?"التواصل والعنوان":"Kontakt & Anfahrt",t("church"),"⌖",`<h2>${state.lang==="ar"?"الأب الكاهن":"Pfarrer"}</h2><p><b>${t("contactPriest")}</b><br><a href="tel:+4915259544511">${t("contactPhone")}</a></p><h2>${state.lang==="ar"?"مقر الكنيسة في شمال ألمانيا":"Hauptsitz der koptisch-orthodoxen Kirchen in Norddeutschland"}</h2><p><b>${t("contactMonastery")}</b><br>${t("contactAddress")}<br><a href="tel:+49527118905">+49 5271 18905</a></p><p>${t("contactBishop")}<br><a href="tel:+491725643647">${t("contactBishopPhone")}</a></p><button class="launch" onclick="window.open('https://koptische-kirche-hamburg.de/kontakt/','_blank')">${state.lang==="ar"?"فتح صفحة التواصل":"Kontaktformular auf Website"}</button>`);
if(["liturgies","events","priests"].includes(route))return contentPage(route==="liturgies"?t("next"):route==="events"?(state.lang==="ar"?"الفعاليات":"Veranstaltungen"):(state.lang==="ar"?"الآباء الكهنة":"Unsere Priester"),t("church"),route==="liturgies"?"♜":route==="events"?"▣":"♟",`<h2>${state.lang==="ar"?"مساحة جاهزة للمحتوى الحقيقي":"Bereich für echte Gemeindedaten"}</h2><p>${state.lang==="ar"?"هذه نسخة تصميمية. سيتم ربط المواعيد والأسماء والمحتوى لاحقاً عبر نظام إدارة المحتوى.":"Design-Prototyp: Termine, Personen und Inhalte werden später über das CMS gepflegt."}</p>`);
if(["bible","reading-plan","agpeya","calendar","favorites"].includes(route))return contentPage(t("spiritual"),t("spiritualSub"),"✚",`<h2>${route.replace("-"," ")}</h2><p>${state.lang==="ar"?"هذه وظيفة مستهدفة للنسخة التالية.":"Ziel-Funktion für die nächste Produktphase."}</p>`);
if(["videos","images","sermons","learning","featured"].includes(route))return contentPage(t("media"),t("mediaSub"),"▶",`<h2>${state.lang==="ar"?"مكتبة الإعلام":"Medienbibliothek"}</h2><p>${state.lang==="ar"?"هنا ستظهر المواد الحقيقية المصنفة حسب النوع واللغة والتاريخ.":"Hier erscheinen später echte Inhalte, filterbar nach Typ, Sprache und Datum."}</p><div class="tag-row"><span class="tag">Deutsch</span><span class="tag">العربية</span><span class="tag">Video</span><span class="tag">Audio</span></div>`);
if(route.startsWith("class"))return classPage(parseInt(route.replace("class",""),10)||0);
if(route==="sunday")return `<section class="ss-page"><div class="ss-banner"><button class="back" onclick="go('home')">‹ ${t("back")}</button><h1>${t("classTitle")}</h1><p>${t("classSub")} — ${t("open")}</p></div><div class="section-head"><h2>${state.lang==="ar"?"اختر المجموعة":"Gruppe auswählen"}</h2></div><div class="card-grid">${t("classes").map((x,i)=>`<button class="feature-card" onclick="go('class${i}')"><img class="class-img" src="${x[3]}" alt="${x[0]}"><h3 style="font-family:Georgia,serif;color:var(--navy);margin:9px 0 2px">${x[0]}</h3><span>${x[2]}</span></button>`).join("")}</div></section>`;
return home();}
function classPage(i){const x=t("classes")[i];return `<section class="ss-page"><div class="ss-banner"><button class="back" onclick="go('home')">‹ ${t("back")}</button><h1>${x[0]}</h1><p>${x[1]} • ${x[2]}</p></div><div class="ss-detail"><img src="${x[3]}" alt="${x[0]}"><div class="ss-detail-body"><h2>${x[0]}</h2><p>${state.lang==="ar"?"معاينة لتطبيق مدرسة الأحد المستقل لهذه المجموعة.":"Vorschau für die separate Sonntagsschule-App dieser Gruppe."}</p><div class="tag-row"><span class="tag">📚 ${state.lang==="ar"?"الدروس":"Lessons"}</span><span class="tag">📖 ${state.lang==="ar"?"القراءة":"Reading"}</span><span class="tag">🎥 ${state.lang==="ar"?"فيديو":"Videos"}</span><span class="tag">🔔 ${state.lang==="ar"?"الإشعارات":"Notifications"}</span></div><button class="launch" onclick="placeholder('${x[0]}')">${t("open")}</button></div></div></section>`}
function placeholder(name){alert((state.lang==="ar"?"هذه معاينة تصميمية فقط: ":"Design-Prototyp: ")+name)}
function render(){document.body.classList.toggle("arabic",state.lang==="ar");document.body.classList.toggle("route-home",state.route==="home");document.documentElement.lang=state.lang;document.getElementById("screen").innerHTML=page(state.route);document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.route===state.route))}
window.addEventListener("hashchange",()=>{state.route=location.hash.replace("#","")||"home";render()});render();
